### PR TITLE
add simple example

### PR DESCRIPTION
**Pull request by Miopas**
Add a very simple example for quickly start.

### CODE REVIEW

**Comment by kylebgorman** [comment]
Thanks for this! Would this work better as part of the README file, though? Let me know what you think and I'll merge it in either form.

**Comment by Miopas** [comment]
@kylebgorman I think it works better as part of the README file. I find the usage by the file 'tests.py' and verify my idea in 'textgrid.py', which is not efficient. 
If you merge it in README, it's not necessary to merge this file. The example is too simple and not complete.
BTW, thanks for this great tool. Really helpful.

**Comment by MorrisXu-Driving** [comment]
It would be really appreciated if a simple example can be added as soon as possible. Thanks!

**Comment by kylebgorman** [comment]
If you want this fix the above pull request along the outlines I mentioned earlier (namely that it belongs in the README, not a random file). Otherwise please resist the urge to do "me too" posts on this thread.

There are plenty of examples in the tests, which you could copy into the README.

**Comment by Miopas** [comment]
> If you want this fix the above pull request along the outlines I mentioned earlier (namely that it belongs in the README, not a random file). There are plenty of examples in the tests, which you could copy into the README.
> 
> I'll be happy to reopen this if anyone volunteers.

Sorry that I just realized that I misunderstood before. Now I think that makes a lot of sense. I will add that to the README file and open another open request.

**Pull request closed without merging**
